on:
  push:
    branches:
      - master

name: deploy-book

jobs:
  bookdown:
    name: Render-Book
    runs-on: macOS-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        
      - name: Setup R
        uses: r-lib/actions/setup-r@master
        
      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@master
      
      - name: Install rmarkdown
        run: |
          install.packages(c("rmarkdown","bookdown"))
        shell: Rscript {0}
      
      - name: Render Book
        run: |
          bookdown::render_book("index.Rmd")
        shell: Rscript {0}
      
      - uses: actions/upload-artifact@v1
        with:
          name: book
          path: book/
  
# Need to first create an empty gh-pages branch
# see https://pkgdown.r-lib.org/reference/deploy_site_github.html
# and also add secrets for a GH_PAT and EMAIL to the repository
# gh-action from Cecilapp/GitHub-Pages-deploy
  checkout-and-deploy:
    name: Deploy Book
    runs-on: ubuntu-latest
    needs: bookdown
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: book
          path: book
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: swnydick@gmail.com
          build_dir: book